default:
  mqtt:
    protocol: mqtt # mqtt, tcp
    addrees: localhost
    port: 1883
    topic: pos-state
    qos:
      level: 1
      retain: true
  client:
    name: app_seller
    dispositive:
      id: 16
    publishState:
      interval:
        timeInMs: 5000 # 60000 = One Minute